server:
  port: 8080

spring:
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/user?useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.hjl.pojo

#打印sql语句
logging:
  level:
    com.hjl.dao: debug # 改成你的mapper文件所在包路径

#将themilef的默认缓存禁用，热加载生效
  thymeleaf:
    cache: false
#redis配置
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: localhost  #Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password: #Redis服务器连接密码（默认为空）
    timeout: 12000 #redis 超时时间
    # password:
    pool:
      minIdle: 1 #redis最小空闲连接
      maxIdle: 10 #redis最大空闲连接
      maxWait: 3 #redis最大阻塞等待时间（负值表示无限制）
      maxActive: 8 #redis最大池连接数
